### ISSUE TITLE
Duplicate Code

### ISSUE THREAD

**Issue by wangje2** [DavidRambo/image_microservice#2]
You have code to create the IMAGES_DIR in both your on_startup and create_images_dir functions. 

def create_images_dir():
    if not os.path.exists(IMAGES_DIR):
        os.mkdir(IMAGES_DIR)

@app.on_event("startup")
def on_startup():
    """Sets up the database on application startup."""
    # TODO: For production, have a migration script (Alembic).
    create_db_and_tables()
    create_images_dir()

**Comment by DavidRambo** [comment]
The `on_startup` function calls `create_images_dir`. So only the latter is actually making that directory.
